# Generated by Django 2.2.5 on 2019-09-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tvg_id', models.CharField(max_length=200)),
                ('epg_id', models.BigIntegerField(default=9999)),
                ('channel_group', models.CharField(max_length=200)),
                ('channel_name', models.CharField(max_length=200)),
                ('channel_url', models.CharField(max_length=1200)),
                ('channel_logo', models.ImageField(blank=True, null=True, upload_to='channel_logos/')),
                ('channel_logo_url', models.URLField(blank=True, null=True)),
                ('channel_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EPGChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChannelName', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start', models.CharField(max_length=400)),
                ('Stop', models.CharField(max_length=400)),
                ('Channel', models.CharField(max_length=400)),
                ('Title', models.CharField(max_length=400)),
                ('Description', models.CharField(max_length=99999, null=True)),
            ],
        ),
    ]
