# Generated by Django 2.2.4 on 2019-09-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tvg_id', models.CharField(default='', editable=False, max_length=200)),
                ('epg_id', models.BigIntegerField(default=9999)),
                ('channel_group', models.CharField(max_length=200)),
                ('channel_name', models.CharField(max_length=200)),
                ('channel_url', models.CharField(max_length=1200)),
                ('channel_logo', models.CharField(max_length=800)),
                ('channel_enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Programmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start', models.CharField(max_length=400)),
                ('Stop', models.CharField(max_length=400)),
                ('Channel', models.CharField(max_length=400)),
                ('Title', models.CharField(max_length=400)),
                ('Description', models.CharField(max_length=99999)),
            ],
        ),
    ]
