# Generated by Django 2.2.4 on 2019-08-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvg_id', models.CharField(max_length=200)),
                ('tvg_name', models.CharField(max_length=200)),
                ('tvg_logo', models.CharField(max_length=800)),
                ('group_title', models.CharField(max_length=200)),
                ('channel_name', models.CharField(max_length=200)),
                ('channel_url', models.CharField(max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='EPGChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=1200)),
                ('display_name', models.CharField(max_length=1200)),
                ('icon_src', models.CharField(max_length=1200)),
                ('lcn', models.CharField(max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='Programmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start', models.DateTimeField()),
                ('Stop', models.DateTimeField()),
                ('Channel', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=400)),
                ('Description', models.CharField(max_length=99999)),
            ],
        ),
    ]
