# Generated by Django 2.2.4 on 2019-08-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_enabled',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
