# Generated by Django 2.2.5 on 2019-09-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20190921_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epgchannels',
            name='ChannelName',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
