# Generated by Django 2.2.4 on 2019-09-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20190901_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmes',
            name='Description',
            field=models.CharField(max_length=99999, null=True),
        ),
    ]
