# Generated by Django 2.2.4 on 2019-08-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_channel_channel_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='epg_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
