# Generated by Django 2.2.4 on 2019-08-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_channel_epg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='epg_id',
            field=models.BigIntegerField(default=99999),
        ),
    ]
