# Generated by Django 2.2.5 on 2019-09-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20190921_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epgchannels',
            name='id',
        ),
        migrations.AlterField(
            model_name='epgchannels',
            name='ChannelName',
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
    ]
