# Generated by Django 2.2.4 on 2019-09-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_auto_20190901_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_logo',
            field=models.ImageField(upload_to='channel_logos/'),
        ),
    ]
