# Generated by Django 2.2.4 on 2019-09-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_auto_20190901_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_logo_url',
            field=models.URLField(null=True),
        ),
    ]
