# Generated by Django 2.2.4 on 2019-09-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_channel_channel_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_logo',
            field=models.ImageField(blank=True, null=True, upload_to='channel_logos/'),
        ),
    ]
