# Generated by Django 2.2.5 on 2019-09-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_auto_20190921_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='tvg_id',
            field=models.CharField(max_length=999),
        ),
    ]
