# Generated by Django 2.2.5 on 2019-09-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0007_auto_20190901_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='tvg_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
