# Generated by Django 2.2.5 on 2019-09-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0008_auto_20190921_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='tvg_id',
            field=models.CharField(default=0, max_length=999),
            preserve_default=False,
        ),
    ]
