# Generated by Django 2.2.5 on 2019-09-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0009_auto_20190921_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_protected',
            field=models.BooleanField(default=False),
        ),
    ]
