# Generated by Django 2.2.5 on 2019-09-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0010_channel_channel_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='stream_active',
            field=models.BooleanField(default=True),
        ),
    ]
